# Generated by Django 5.0.8 on 2024-08-07 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('bio', models.TextField(help_text='Enter a brief biography of the blogger', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(help_text='Enter content of the blog', max_length=2000)),
                ('post_date', models.DateField(blank=True, null=True)),
                ('blogger', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.blogger')),
            ],
        ),
    ]
